### ISSUE TITLE
TODO - Database (MongoDB) Implementation

### ISSUE THREAD

**Issue by ethanlindley** [ethanlindley/lego.py#1]
- [x] Begin database logic, decide on a database engine (MongoDB)
- [x] Allow database to be accessed dynamically across servers
- [ ] **MAJOR**: fix storing/retrieval of hashed and salted passwords
- [x] Test database with auth-related objects (accounts)
- [ ] Test database with game objects and components (CDClient)

**Comment by ethanlindley** [comment]
I could possibly look into other options for the engine of the server's database, but I really enjoy the speed that Mongo provides (and really any non-relational database compared to common relational databases)

**Comment by ethanlindley** [comment]
Databases are able to be accessed dynamically thanks to changes made in commit b5d10f8cb08c5cdb70708b82ebca5f653cd6bbcc

**Comment by ethanlindley** [comment]
Login works almost 100% with database implementation properly retrieving and adding account objects to the database as of commit b071dcec95ded004e8b4dd37c50fc76643558ac6

**Comment by ethanlindley** [comment]
I'd like to get the hashing/salting issue sorted out ASAP, I've had trouble getting the data to stay consistent across the server and database (pword changes when sent to db after being created server side?)
